### ISSUE TITLE
The task hangs if it can not access the file

### ISSUE THREAD

**Issue by Albeoris** [emerbrito/ILMerge-MSBuild-Task#16]
**It's a corner case.**

If you block yourself:
`"OutputFile": "$(TargetDir)$(TargetFileName)"`

The builder will hang, MSBuild.exe will continue to hold the symbol file (.pdb)

**Comment by emerbrito** [comment]
I will see if I can run some simulations and eventually figure out a way to prevent it.

**Comment by Suplanus** [comment]
Same problem here...
Could it be that for example Fody.PropertyChanged use the file and ilmerge should wait for finishing weaving?

**Comment by emerbrito** [comment]
I took another look at this but I'm still unable to come up with a solution.
This same issue has been reported through years all over the place by people using ILMerge who wants/needs ILMerge output to override Visual Studio output.

For reasons I still don't know the pdb files are locked and the whole thing goes south.

The easiest (and most obvious) solutions are:

_**If you need PDB files as part of your output your have two options:**_

1. Use a different name:
`OutputFile": "$(TargetDir)MyCustomName.dll`
2. Use a different output folder - default behavior, no changes needed.

_**If you want to use "$(TargetDir)$(TargetFileName)" but don't need the PDB files:**_

Add the following to your configuration file. This will instruct ILMerge to ignore PDB files.

    "Advanced": {
        "DebugInfo": false
    }

While the above is not a fix for the issue, they seem pretty reasonable workarounds.

**Comment by emerbrito** [comment]
It seems this is caused by ilmerge itself and there is no viable solution other then the workarounds provided here.
