### ISSUE TITLE
ILMerge.MSBuild.Task.targets incompatible with VS2017

### ISSUE THREAD

**Issue by ghost** [emerbrito/ILMerge-MSBuild-Task#18]
It seems that we need a minor modification to the file in order for VS2017 to recognize it properly.
When loading the target file, MSBuild shipped with VS2017 complains that the `%(CopyLocal)` should be qualified as `%(ReferencePath.CopyLocal)`.
There are two places in the file to which this qualification applies.
I would be glad if you could update the nuget package with this fix applied, though the fix is still possible at the project level after installing the package.
I thought it was overkill to fork the entire repository and issue a pull request just for this fix.
Thank you in advance.

**Comment by emerbrito** [comment]
Could you please give me more details on when and where you see this error? I've been running this on VS2017 for a while (actually I use VS2017 since it came out) and I don't have any issues. I will be glad to fix (ASAP) it when I understand where and why exactly it is happening.

**Comment by emerbrito** [comment]
Closed due to inactivity. Please feel free to reopen it if the issue persists.
