### ISSUE TITLE
wiki - Content string escape

### ISSUE THREAD

**Issue by pzhlkj6612** [emerbrito/ILMerge-MSBuild-Task#19]
The table in [Escaping Content # Config File · emerbrito/ILMerge-MSBuild-Task Wiki · GitHub](https://github.com/emerbrito/ILMerge-MSBuild-Task/wiki/Config-File#escaping-content):

Original Path | Escaped Path
--- | ---
C:\MyFolder\MyLib.dll | C:\MyFolder\MyLib.dll

should be,

Original Path | Escaped Path
--- | ---
C:\MyFolder\MyLib.dll | C:\\\\MyFolder\\\\MyLib.dll

Well, raw content (`C:\\\\MyFolder\\\\MyLib.dll`) will look strange because of the string escape rule of Markdown.

**Comment by emerbrito** [comment]
Good catch, thank you.

**Comment by emerbrito** [comment]
Documentation updated. Fixed.
