### ISSUE TITLE
Multiple Projects in Solution 

### ISSUE THREAD

**Issue by xi-osman** [emerbrito/ILMerge-MSBuild-Task#20]
How can I specify to only use ILMerge on one Project rather all projects? getting an error of conflicts.

**Comment by emerbrito** [comment]
When you install the nuget package (ILMerge-MSBuild-Task) it is usually installed on a context of a project. Could you please provide more details of your implementation?

**Comment by xi-osman** [comment]
So I have one solution with 2 projects, C# Plugin project for CRM and one Unit Test project. I installed (ILMerge-MSBuild-Task) on the C# Plugin project but when the Unit Test tries to build it gets an error that the same dll is already referenced. So to fix this I have to remove the 'xrm.sdk...' reference from the Unit Test even though I get the red syntax errors of missing assemblies but it will build. 

So I have a work around. But I was just wondering if I set this up wrong.

**Comment by emerbrito** [comment]
It should work just fine. It sounds like an issue with your setup.
If you can please setup a quick test project (or download the one below):

1. Create a Plugin Project (c# project) (could be an empty plugin).
2. Add the required nuget packages (including CRM SDK)
3. Create the test project
4. In the test project add a reference to your Plugin Project.
5. In the test project, add the nuget packages required by your plugin (such as CRM SDK), DO NOT ADD ILMerge-MSBuild-Task.
6. Run the tests and build your project.

Attached is a simple project I just created using above steps - in case you want to download and give it a try. It works as expected.

[MyCrmPlugin.zip](https://github.com/emerbrito/ILMerge-MSBuild-Task/files/2605654/MyCrmPlugin.zip)

**Comment by xi-osman** [comment]
Thanks @emerbrito. I will take a look at it!

**Comment by emerbrito** [comment]
Closed due to inactivity. Please feel free to reopen it if the issue persists.
