### ISSUE TITLE
ABout box auto override by content of other dll

### ISSUE THREAD

**Issue by thelemontree10** [emerbrito/ILMerge-MSBuild-Task#21]
Dear Emerbrito,

Your dll is very good. Thanks for your help.

When I use you nuget, every dll is merged ok into one exe and the app is doing well, except for problem below.

I use NLog for tracking log in my app. When run app, this dll overide the content in my "About Box" (default form of Winform).

https://flic.kr/p/29Sp871

Can you fix this ? Thank you.

Best Regards,

**Comment by emerbrito** [comment]
I'm assuming the information you want to see is being entered by manually editing the "AssemblyInfo.cs" file or by following these steps:

- Opening the project and double clicking on the "Properties" node.
- Then in the "Application" tab clicking in "Assembly Information".

If this is what you are doing, after everything is merged as a single file (.exe based on your post), if you right click the merged file (executable) and go to "Properties/Details". Do you still see the NLog information or is it displaying the correct properties?

If it is displaying the right properties the issue must be related to how your "About Box" is reading the data which unfortunately I cannot help with. Please let me know.

**Comment by emerbrito** [comment]
Closed due to inactivity. Please feel free to reopen it if the issue persists.
