### ISSUE TITLE
Need for UserProfile variable with ILMergeConfig.json (for using PackageReference format)

### ISSUE THREAD

**Issue by ashwinravi** [emerbrito/ILMerge-MSBuild-Task#22]
I changed all my Nuget references from the packages.config format to use the PackageReference format (https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference) which offers quite a few advantages. This means that I don't have any packages folder within my VS solution or project structure to reference within my ILMergeConfig.json file. Instead I need to be able to reference the global-packages folder which generally resides here:
   Windows: %userprofile%\.nuget\packages
   Mac/Linux: ~/.nuget/packages

Is there a config variable for UserProfile for both PC and MACs that I can use to reference my InputAssemblies and also to specify an AlternativeILMergePath in the ILMergConfig.json file?

**Comment by emerbrito** [comment]
This was addressed as part of #23.
Shipped with v1.0.5.
