### ISSUE TITLE
ILMergeConfig.json is not applied

### ISSUE THREAD

**Issue by khoait** [emerbrito/ILMerge-MSBuild-Task#25]
Hi,

I'm using v1.0.5 in VS 2017. I created ILMergeConfig.json in project root folder and specified InputAssembies.

When I build the project, it doesn't apply the config json file and always merge Copy Local = True assemblies.

Did I miss any step?

**Comment by emerbrito** [comment]
That is the same setup I use to create Dynamics 365 plugins and never had an issue.
Is ILMergeConfig.json in the project root or solution root (in case they are different)? It should be in the project root folder.

This is how we locate the json file (a snippet from the .target):
````
ConfigurationFilePath="$(ProjectDir)ILMergeConfig.json"
````

As long as it in the same folder as your .csproj file (visual studio project file) it should work.
Please let me know if you still experiencing the issue and hopefully we will figure it out.

**Comment by khoait** [comment]
Yeah, I still experience the issue. Please review my screen record below.

![ilmerge](https://user-images.githubusercontent.com/8686497/57121290-bcb9d100-6da0-11e9-9135-163505fb9e51.gif)

**Comment by khoait** [comment]
Thanks @emerbrito ,

I removed the ILMerge-MSBuild-Task and the ILMerge nuget package, and installed them again. Clean and Rebuild the solution. It's working now.
