### ISSUE TITLE
NullReferenceExceptions when using a config file

### ISSUE THREAD

**Issue by slahn** [emerbrito/ILMerge-MSBuild-Task#7]
I've had to add the following to our config file in order to avoid Null reference exceptions when merging:

    "Advanced": {
      "SearchDirectories" :  []
    }

**Comment by slahn** [comment]
This is because constructors are not run when using DataContractSerializer.

You could implement initialization methods and use `[OnDeserializing]`, or you could switch to Newtonsoft.Json.

I'm happy to supply a pull request for either of them. Which would you prefer?

**Comment by emerbrito** [comment]
I believe Newtonsoft.Json might be overkill for this. If you provide the pull request I will be more than happy to merge it. Otherwise I will work on it mid next week.
Thanks for your help.

**Comment by emerbrito** [comment]
Replaced Newtonsoft.Json with `JavaScriptSerializer` (from `System.Web.Script.Serialization`) to prevent having to load the third party assembly during build.
